--liquibase formatted sql
--changeset skot:8
INSERT INTO public.subject(name, short_name) VALUES ('biologia', 'BIO');
INSERT INTO public.subject(name, short_name) VALUES ('biologia R', 'BIO R');
INSERT INTO public.subject(name, short_name) VALUES ('biznes i zarządzanie', 'BIZ');
INSERT INTO public.subject(name, short_name) VALUES ('chemia', 'CHE');
INSERT INTO public.subject(name, short_name) VALUES ('chemia R', 'CHE R');
INSERT INTO public.subject(name, short_name) VALUES ('doradztwo zawodowe', 'DZ');
INSERT INTO public.subject(name, short_name) VALUES ('edukacja dla bezpieczeństwa', 'EDB');
INSERT INTO public.subject(name, short_name) VALUES ('etyka', 'ETY');
INSERT INTO public.subject(name, short_name) VALUES ('filozofia', 'FIL');
INSERT INTO public.subject(name, short_name) VALUES ('fizyka', 'FIZ');
INSERT INTO public.subject(name, short_name) VALUES ('fizyka R', 'FIZ R');
INSERT INTO public.subject(name, short_name) VALUES ('geografia', 'GEO');
INSERT INTO public.subject(name, short_name) VALUES ('geografia R', 'GEO R');
INSERT INTO public.subject(name, short_name) VALUES ('godzina wychowawcza', 'GW');
INSERT INTO public.subject(name, short_name) VALUES ('historia', 'H');
INSERT INTO public.subject(name, short_name) VALUES ('historia R', 'H R');
INSERT INTO public.subject(name, short_name) VALUES ('historia i teraźniejszość', 'HIT');
INSERT INTO public.subject(name, short_name) VALUES ('historia sztuki R', 'HSZ R');
INSERT INTO public.subject(name, short_name) VALUES ('informatyka', 'INF');
INSERT INTO public.subject(name, short_name) VALUES ('informatyka R', 'INF R');
INSERT INTO public.subject(name, short_name) VALUES ('język angielski', 'JA');
INSERT INTO public.subject(name, short_name) VALUES ('język francuski', 'JF');
INSERT INTO public.subject(name, short_name) VALUES ('język francuski R', 'JF R');
INSERT INTO public.subject(name, short_name) VALUES ('język hiszpański', 'JH');
INSERT INTO public.subject(name, short_name) VALUES ('język hiszpański R', 'JH R');
INSERT INTO public.subject(name, short_name) VALUES ('język niemiecki', 'JN');
INSERT INTO public.subject(name, short_name) VALUES ('język niemiecki R', 'JN R');
INSERT INTO public.subject(name, short_name) VALUES ('język polski', 'JP');
INSERT INTO public.subject(name, short_name) VALUES ('język polski R', 'JP R');
INSERT INTO public.subject(name, short_name) VALUES ('język rosyjski', 'JR');
INSERT INTO public.subject(name, short_name) VALUES ('matematyka', 'MAT');
INSERT INTO public.subject(name, short_name) VALUES ('matematyka R', 'MAT R');
INSERT INTO public.subject(name, short_name) VALUES ('podstawy przedsiębiorczości', 'PP');
INSERT INTO public.subject(name, short_name) VALUES ('religia', 'REL');
INSERT INTO public.subject(name, short_name) VALUES ('wiedza o społeczeństwie', 'WOS');
INSERT INTO public.subject(name, short_name) VALUES ('wiedza o społeczeństwie R', 'WOS R');
INSERT INTO public.subject(name, short_name) VALUES ('wychowanie fizyczne', 'WF');
INSERT INTO public.subject(name, short_name) VALUES ('zajęcia z psychologiem', 'ZZP');